/**
 * The Worker's bindings and secrets.
 *
 * `Env` is generated by `wrangler types` from wrangler.jsonc and covers the
 * bindings (ASSETS, SESSIONS). The six OAuth credentials are secrets rather than
 * config, so they are declared here explicitly: that keeps them type-checked
 * without depending on whether typegen happened to see a local .dev.vars.
 */
export interface AppEnv extends Env {
  TWITCH_CLIENT_ID: string
  TWITCH_CLIENT_SECRET: string
  KICK_CLIENT_ID: string
  KICK_CLIENT_SECRET: string
  VKVIDEO_CLIENT_ID: string
  VKVIDEO_CLIENT_SECRET: string
}
